db.url=jdbc:mysql://localhost:3306/finsmart_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=YOUR_PASSWORD_HERE (pass này là pass root MySQL của ae)
db.driver=com.mysql.cj.jdbc.Driver